# Generated by Django 3.2.7 on 2022-06-09 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_no', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('father_name', models.CharField(blank=True, max_length=254, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=254, null=True)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=10)),
                ('spouse_name', models.CharField(blank=True, max_length=254, null=True)),
                ('age', models.DateField()),
                ('blood_group', models.CharField(choices=[('B+', 'B+'), ('B-', 'B-'), ('A+', 'A+'), ('A-', 'A-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('OB+', 'OB+'), ('OB-', 'OB-')], max_length=10)),
                ('occupation', models.CharField(blank=True, max_length=254, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='prescription/image/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='prescription/pdf')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamber.profile')),
            ],
        ),
    ]
