# Generated by Django 3.2.7 on 2022-06-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0002_alter_prescription_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='htid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
