# Generated by Django 3.2.7 on 2022-06-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0003_profile_htid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='htid',
            new_name='hiveid',
        ),
    ]
