# Generated by Django 3.2.7 on 2022-06-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0008_auto_20220611_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='book_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
