# Generated by Django 3.2.7 on 2022-06-11 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chamber', '0009_alter_profile_book_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='book_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chamber.bookno'),
        ),
    ]
